version: '3.8'

services:
  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  mongoexpress:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
      - ME_CONFIG_MONGODB_SERVER=mongo
    depends_on:
      - mongo
    restart: always

  task-batch-processor-service:
    build:
      context: ./apps/task-batch-processor-service
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./apps/task-batch-processor-service:/app  # Maps the code to local machine
      - /app/node_modules    # Keeps node_modules in the container
    environment:
      - MONGODB_URI=mongodb+srv://misemind:4k8jvV0Ov3tuLwCl@cluster-0.4h0sdof.mongodb.net/proactforge/?retryWrites=true&w=majority&appName=cluster-0
      - NODE_ENV=development
      - MINIO_ENDPOINT=minio
      - MINIO_PORT=9000
      - MINIO_USE_SSL=false
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    # depends_on:
    #   - mongo
    #   - minio
    command: >
      sh -c "pnpm install && pnpm run start:dev"  # Ensure dependencies are installed and run in dev mode

  task-management-service:
    build:
      context: ./apps/task-management-service
      dockerfile: Dockerfile
    ports:
      - '4000:3000'
    volumes:
      - ./apps/task-management-service:/app  # Maps the code to local machine
      - /app/node_modules    # Keeps node_modules in the container
    environment:
      - MONGODB_URI=mongodb+srv://misemind:4k8jvV0Ov3tuLwCl@cluster-0.4h0sdof.mongodb.net/proactforge/?retryWrites=true&w=majority&appName=cluster-0
      - NODE_ENV=development
      - MINIO_ENDPOINT=minio
      - MINIO_PORT=9000
      - MINIO_USE_SSL=false
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    # depends_on:
    #   - mongo
    #   - minio
    command: >
      sh -c "pnpm install && pnpm run start:dev"  # Ensure dependencies are installed and run in dev mode

  # web:
  #   build:
  #     context: ./apps/web
  #     dockerfile: Dockerfile
  #   ports:
  #     - '3001:3000'
  #   volumes:
  #     - ./apps/web:/app
  #     - /app/node_modules
  #   environment:
  #     - NODE_ENV=development  
  #   depends_on:
  #     - mongo
  #     - minio
  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
  #   container_name: elasticsearch
  #   environment:
  #     - node.name=elasticsearch
  #     - discovery.type=single-node
  #     - bootstrap.memory_lock=true
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #     - xpack.security.enabled=false
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   volumes:
  #     - esdata:/usr/share/elasticsearch/data
  #   ports:
  #     - "9200:9200"

  # logstash:
  #   image: docker.elastic.co/logstash/logstash:7.15.0
  #   container_name: logstash
  #   volumes:
  #     - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
  #   ports:
  #     - "5000:5000"
  #     - "9600:9600"
  #   depends_on:
  #     - elasticsearch

  # kibana:
  #   image: docker.elastic.co/kibana/kibana:7.15.0
  #   container_name: kibana
  #   environment:
  #     ELASTICSEARCH_URL: http://elasticsearch:9200
  #     ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
  #   ports:
  #     - "5601:5601"
  #   depends_on:
  #     - elasticsearch    

volumes:
  mongo-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /Users/vikasbansal/mongo-data
  minio-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /Users/vikasbansal/minio-data
  ollama:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /Users/vikasbansal/ollama_data
  webui_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /Users/vikasbansal/webui_data
  esdata:
    driver: local    
