export type Task = {
    id: number;           // Unique identifier for each task
    title: string;        // Title or name of the task
    description?: string; // Detailed description of the task
    assignedTo: string;   // Name of the person responsible for the task
    dueDate: string;      // Due date for the task (ISO 8601 format, e.g., '2024-09-20')
    priority: 'low' | 'medium' | 'high'; // Task priority
    status: 'pending' | 'in-progress' | 'completed'; // Status of the task
    completed: boolean;   // New boolean field to indicate whether the task is completed
  };
  
  export const tasks: Task[] = [
    {
      id: 1,
      title: 'Complete report',
      description: 'Complete the quarterly financial report.',
      assignedTo: 'Dylan Murray',
      dueDate: '2024-09-30',
      priority: 'high',
      status: 'in-progress',
      completed: false,
    },
    {
      id: 2,
      title: 'Fix website bugs',
      description: 'Resolve the reported issues on the homepage.',
      assignedTo: 'Ervin Reinger',
      dueDate: '2024-09-25',
      priority: 'medium',
      status: 'pending',
      completed: false,
    },
    {
      id: 3,
      title: 'Prepare presentation',
      description: 'Prepare the slides for the upcoming product launch.',
      assignedTo: 'Raquel Kohler',
      dueDate: '2024-09-28',
      priority: 'high',
      status: 'completed',
      completed: true,
    },
    {
      id: 4,
      title: 'Deploy new release',
      description: 'Deploy the new version of the application to the production server.',
      assignedTo: 'Branson Frami',
      dueDate: '2024-09-22',
      priority: 'high',
      status: 'pending',
      completed: false,
    },
    {
      id: 5,
      title: 'Create project plan',
      description: 'Draft the project plan for the next quarter.',
      assignedTo: 'Brittany McCullough',
      dueDate: '2024-10-01',
      priority: 'medium',
      status: 'in-progress',
      completed: false,
    },
    {
      id: 6,
      title: 'Update task board',
      description: 'Update the task board with recent project status changes.',
      assignedTo: 'Raquel Kohler',
      dueDate: '2024-09-24',
      priority: 'low',
      status: 'completed',
      completed: true,
    },
    {
      id: 7,
      title: 'Test new feature',
      description: 'Perform QA testing on the new feature branch.',
      assignedTo: 'Dylan Murray',
      dueDate: '2024-09-27',
      priority: 'medium',
      status: 'pending',
      completed: false,
    },
    {
      id: 8,
      title: 'Fix login issue',
      description: 'Resolve the bug preventing users from logging into the system.',
      assignedTo: 'Ervin Reinger',
      dueDate: '2024-09-23',
      priority: 'high',
      status: 'completed',
      completed: true,
    },
    {
      id: 9,
      title: 'Prepare client meeting',
      description: 'Prepare the agenda and materials for the client meeting.',
      assignedTo: 'Brittany McCullough',
      dueDate: '2024-09-21',
      priority: 'high',
      status: 'completed',
      completed: true,
    },
    {
      id: 10,
      title: 'Submit project report',
      description: 'Finalize and submit the monthly project report.',
      assignedTo: 'Branson Frami',
      dueDate: '2024-09-26',
      priority: 'medium',
      status: 'pending',
      completed: false,
    },
    {
      id: 11,
      title: 'Conduct performance review',
      description: 'Annual performance review for team members.',
      assignedTo: 'Brittany McCullough',
      dueDate: '2024-09-15',
      priority: 'high',
      status: 'completed',
      completed: true,
    },
    {
      id: 12,
      title: 'Backup database',
      description: 'Complete backup of the company database.',
      assignedTo: 'Ervin Reinger',
      dueDate: '2024-09-16',
      priority: 'medium',
      status: 'completed',
      completed: true,
    },
    {
      id: 13,
      title: 'Review security audit',
      description: 'Analyze and review the findings from the recent security audit.',
      assignedTo: 'Raquel Kohler',
      dueDate: '2024-09-18',
      priority: 'high',
      status: 'completed',
      completed: true,
    },
    {
      id: 14,
      title: 'Send client invoice',
      description: 'Send the invoice to the client for the last project.',
      assignedTo: 'Branson Frami',
      dueDate: '2024-09-19',
      priority: 'medium',
      status: 'completed',
      completed: true,
    },
  ];
  